version: '3.7'

services:
  app:
    build:
      context: .
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    ports:
      - '4000:4000'
    command: yarn dev
